# -*- coding: utf-8 -*-
"""ASR_Project_Whisper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MxJ-0L2oJ4XS5bXtbxUahY4uZ55wNpG1
"""

!pip install -q openai-whisper
!pip install -q faster-whisper
!pip install -q transformers datasets evaluate jiwer torchaudio psutil

import torch
import time
import psutil
import os
import numpy as np
import pandas as pd

from datasets import load_dataset
from jiwer import wer

print("GPU Available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))
    print("CUDA Version:", torch.version.cuda)

from datasets import load_dataset, Audio

dataset = load_dataset(
    "librispeech_asr",
    "clean",
    split="test[:50]"
)

dataset = dataset.cast_column("audio", Audio(sampling_rate=16000))

print("Total Samples:", len(dataset))

import whisper

device = "cuda" if torch.cuda.is_available() else "cpu"

whisper_model = whisper.load_model("small").to(device)
print("Model loaded successfully.")

import re

def normalize_text(text):
    text = text.lower()
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

results = []

for idx, sample in enumerate(dataset):
    audio = sample["audio"]["array"]
    sr = sample["audio"]["sampling_rate"]
    reference = sample["text"]

    audio_duration = len(audio) / sr

    start_time = time.time()
    result = whisper_model.transcribe(audio)
    prediction = result["text"]
    inference_time = time.time() - start_time

    reference_norm = normalize_text(reference)
    prediction_norm = normalize_text(prediction)

    sample_wer = wer(reference_norm, prediction_norm)
    rtf = inference_time / audio_duration

    results.append({
        "id": idx,
        "wer": sample_wer,
        "inference_time": inference_time,
        "audio_duration": audio_duration,
        "rtf": rtf
    })

    print(f"Processed sample {idx}")

df = pd.DataFrame(results)

print("\n--- FINAL RESULTS ---")
print("Average WER:", df["wer"].mean())
print("Average Inference Time:", df["inference_time"].mean())
print("Average RTF:", df["rtf"].mean())